#!/usr/bin/env python3
"""Generate exact moment-curve H-representations and Haskell regression tests.

stdlib-only oracle: a supporting hyperplane is the cofactor null vector of
(d-1) point differences. Keep planes containing d chosen points only if all
other points lie on one side; orient Ax <= b and primitive-normalize integers.
Usage: python3 tropical-cyclic-oracle.py > TLRSCyclic.hs
"""
from itertools import combinations
from math import gcd
from functools import reduce


def determinant(a):
    if not a:
        return 1
    return sum((-1) ** j * x * determinant([r[:j] + r[j+1:] for r in a[1:]])
               for j, x in enumerate(a[0]))


def fixture(n, d):
    points = [tuple(t ** k for k in range(1, d + 1)) for t in range(1, n + 1)]
    planes = set()
    for chosen in combinations(points, d):
        differences = [[x-y for x, y in zip(p, chosen[0])] for p in chosen[1:]]
        normal = [(-1) ** j * determinant([r[:j] + r[j+1:] for r in differences])
                  for j in range(d)]
        if not any(normal):
            continue
        bound = sum(a*x for a, x in zip(normal, chosen[0]))
        residuals = [sum(a*x for a, x in zip(normal, p)) - bound for p in points]
        if all(x <= 0 for x in residuals):
            pass
        elif all(x >= 0 for x in residuals):
            normal, bound = [-x for x in normal], -bound
        else:
            continue
        divisor = reduce(gcd, [abs(x) for x in normal] + [abs(bound)])
        planes.add(tuple(x // divisor for x in normal) + (bound // divisor,))
    return points, sorted(planes)


def hs_list(values):
    return '[' + ','.join(hs_list(x) if isinstance(x, (tuple, list)) else str(x) for x in values) + ']'


print('''-- Generated by tropical-cyclic-oracle.py using exact integer determinants.
module TGeometry.TLRSCyclic (testsLRSCyclic) where

import Control.Monad (forM_)
import Data.List (sort)
import Data.Matrix (fromLists)
import Geometry.LRS (colFromList, lrs)
import Test.Tasty (TestTree, localOption, mkTimeout, testGroup)
import Test.Tasty.HUnit (assertEqual, testCase)

type Point = [Rational]
type Row = (Point, Rational)

checkFixture :: String -> [Row] -> [Point] -> TestTree
checkFixture name rows points = testGroup name
    [ testCase "all starting vertices" $ check rows points
    , testCase "reversed rows from first, middle and last vertices" $
        check (reverse rows) [head points, points !! (length points `div` 2), last points]
    ]
  where
    check constraints starts = forM_ starts $ \\start ->
        assertEqual ("starting vertex " ++ show start) (sort points)
            (lrs (fromLists (map fst constraints))
                 (colFromList (map snd constraints)) start)

-- Every moment-curve input is an extreme point. Expected vertices are
-- constructed directly from t, independently of the supporting-plane oracle.
''')
for n, d in [(6, 3), (8, 4)]:
    points, planes = fixture(n, d)
    expected_facets = 2*n-4 if d == 3 else n*(n-3)//2
    assert len(planes) == expected_facets
    name = f'cyclic{n}D{d}'
    print(f'{name} :: TestTree')
    print(f'{name} = checkFixture "cyclic C({n},{d})" rows points')
    print('  where')
    print(f'    points = [[t^k | k <- [1..{d} :: Int]] | t <- [1..{n}]]')
    print('    rows =')
    for i, plane in enumerate(planes):
        print('        ' + ('[' if i == 0 else ',') + f'({hs_list(plane[:-1])},{plane[-1]})')
    print('        ]\n')
print('''testsLRSCyclic :: TestTree
testsLRSCyclic = localOption (mkTimeout 30000000) $
    testGroup "LRS cyclic polytopes" [cyclic6D3, cyclic8D4]
''')
