# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: tropical-geometry
version: '0.0.0.1'
github: "ferzcam/tropical-geometry"
license: GPL-3
author: "Fernando Zhapa"
maintainer: "Fernando Zhapa"
# synopsis: A new Haskeleton package.
# description: Tropical is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
#- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  exposed-modules:
  - Polynomial.Monomial
  - Polynomial.Prelude
  - Polynomial.Hypersurface
  - Arithmetic.Numbers
  - Arithmetic.Matrix
  - Geometry.ConvexHull2
  - Geometry.ConvexHull3
  - Geometry.Polytope
  - Geometry.Polyhedral
  - Graphics.Drawings
  - Core
 
  dependencies:
  - base
  - containers
  - numeric-prelude
  - semiring-simple
  - sized
  - algebra
  - singletons-base
  - type-natural
  - lens
  - matrix
  - gloss
  source-dirs: library


executables:
  tropical-geometry:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - tropical-geometry
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -freverse-errors
benchmarks:
  tropical-geometry-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - tropical-geometry
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -freverse-errors
tests:
  tropical-geometry-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    # - Tropical
    - tasty
    - tasty-hspec
    - tasty-hunit
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -freverse-errors
