'use strict';
const $=x=>document.getElementById(x),E={standard:[[0,0,0,0,'0'],[1,0,0,0,'0'],[0,1,0,0,'0'],[0,0,1,0,'0'],[0,0,0,1,'1']],lifted:[[0,0,0,0,'0'],[1,0,0,0,'0'],[0,1,0,0,'0'],[0,0,1,0,'0'],[0,0,0,1,'1'],[1,1,1,0,'1']],flat:[[0,0,0,0,'0'],[0,0,0,1,'1']]};let ts=E.standard,h='0',yaw=-.6,pitch=.5,last,data,rev=0,ac;
function n(s){let p=String(s).split('/');return +p[0]/+(p[1]||1)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function solve(a,b,c){let A=a.slice(0,3),B=b.slice(0,3),C=c.slice(0,3),x=cross(B,C),y=cross(C,A),z=cross(A,B),d=dot(A,x);return Math.abs(d)<1e-9?null:[(a[3]*x[0]+b[3]*y[0]+c[3]*z[0])/d,(a[3]*x[1]+b[3]*y[1]+c[3]*z[1])/d,(a[3]*x[2]+b[3]*y[2]+c[3]*z[2])/d]}
function poly(p,L){let e=p.equality,Q=[+e.a,+e.b,+e.c,n(e.bound)],B=p.inequalities.map(q=>[+q.a,+q.b,+q.c,n(q.bound)]).concat([[1,0,0,L],[-1,0,0,L],[0,1,0,L],[0,-1,0,L],[0,0,1,L],[0,0,-1,L]]),P=[];for(let i=0;i<B.length;i++)for(let j=i+1;j<B.length;j++){let v=solve(Q,B[i],B[j]);if(v&&B.every(q=>dot(q,v)<=q[3]+1e-7)&&!P.some(u=>Math.hypot(...u.map((x,k)=>x-v[k]))<1e-6))P.push(v)}if(P.length<3)return[];let c=[0,1,2].map(k=>P.reduce((s,v)=>s+v[k],0)/P.length),nn=Q.slice(0,3),z=Math.hypot(...nn);nn=nn.map(x=>x/z);let u=cross(Math.abs(nn[2])<.9?[0,0,1]:[0,1,0],nn),ul=Math.hypot(...u);u=u.map(x=>x/ul);let v=cross(nn,u);return P.sort((a,b)=>Math.atan2(dot(a.map((x,k)=>x-c[k]),v),dot(a.map((x,k)=>x-c[k]),u))-Math.atan2(dot(b.map((x,k)=>x-c[k]),v),dot(b.map((x,k)=>x-c[k]),u)))}
function project(p,w,h,s){let cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=cy*p[0]-sy*p[2],z=sy*p[0]+cy*p[2],y=cp*p[1]-sp*z;return[w/2+s*x,h/2-s*y,sp*p[1]+cp*z]}
function volumeFaces(p,L){let B=p.inequalities.map(q=>[+q.a,+q.b,+q.c,n(q.bound)]).concat([[1,0,0,L],[-1,0,0,L],[0,1,0,L],[0,-1,0,L],[0,0,1,L],[0,0,-1,L]]),V=[];for(let i=0;i<B.length;i++)for(let j=i+1;j<B.length;j++)for(let k=j+1;k<B.length;k++){let q=solve(B[i],B[j],B[k]);if(q&&B.every(a=>dot(a,q)<=a[3]+1e-7)&&!V.some(a=>Math.hypot(...a.map((x,m)=>x-q[m]))<1e-6))V.push(q)}let faces=[];for(let b of B){let P=V.filter(q=>Math.abs(dot(b,q)-b[3])<1e-6);if(P.length<3)continue;let c=[0,1,2].map(k=>P.reduce((s,q)=>s+q[k],0)/P.length),nn=b.slice(0,3),z=Math.hypot(...nn);if(!z)continue;nn=nn.map(x=>x/z);let u=cross(Math.abs(nn[2])<.9?[0,0,1]:[0,1,0],nn),ul=Math.hypot(...u);u=u.map(x=>x/ul);let v=cross(nn,u);P.sort((a,d)=>Math.atan2(dot(a.map((x,k)=>x-c[k]),v),dot(a.map((x,k)=>x-c[k]),u))-Math.atan2(dot(d.map((x,k)=>x-c[k]),v),dot(d.map((x,k)=>x-c[k]),u)));faces.push(P)}return faces}
function draw(){let c=$('plot'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let g=c.getContext('2d'),w=r.width,h=r.height,L=5.5,s=Math.min(w,h)*.38/L;g.scale(d,d);g.clearRect(0,0,w,h);if(!data)return;let ps=[];data.patches.forEach((p,i)=>{let e=p.equality,vol=Math.hypot(+e.a,+e.b,+e.c)<1e-10,F=vol?volumeFaces(p,L):[poly(p,L)];F.forEach(P=>{if(P.length>2)ps.push({i,P:P.map(q=>project(q,w,h,s))})})});ps.sort((a,b)=>a.P.reduce((s,p)=>s+p[2],0)-b.P.reduce((s,p)=>s+p[2],0));ps.forEach(q=>{g.beginPath();g.moveTo(q.P[0][0],q.P[0][1]);q.P.slice(1).forEach(p=>g.lineTo(p[0],p[1]));g.closePath();g.fillStyle=['#21816d66','#dc824766','#6374b866','#be608766'][q.i%4];g.strokeStyle=['#21816d','#dc8247','#6374b8','#be6087'][q.i%4];g.fill();g.stroke()})}
async function update(v){let id=++rev;ac&&ac.abort();ac=new AbortController();try{h=String(v).trim();if(!/^-?[0-9]{1,18}(\/[1-9][0-9]{0,17})?$/.test(h))throw Error('Use an integer or exact fraction.');$('hv').textContent=h;$('exact').value=h;$('status').textContent='Computing exact slicf  y  y ';let terms=ts.map(t=>({x:t[0],y:t[1],z:t[2],w:t[3],coefficient:t[4]})),r=await fetch('/api/slice4',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({terms,height:h}),signal:ac.signal}),j=await r.json();if(id!==rev)return;if(!r.ok)throw Error(j.error);data=j;draw();$('status').textContent='w = '+h+'   '+j.patches.length+' exact patches'}catch(e){if(id===rev&&e.name!=='AbortError')$('status').textContent=e.message}}
function showTerms(){$('terms-input').value=JSON.stringify(ts.map(t=>({x:t[0],y:t[1],z:t[2],w:t[3],coefficient:t[4]})),null,2);$('terms').textContent=ts.map((t,i)=>(i+1)+': '+t.join(', ')).join('\n')}
function choose(){if(!E[$('example').value])return;ts=E[$('example').value];$('formula').textContent='min of '+ts.length+' terms';showTerms();update('0')}
$('draw-terms').onclick=()=>{try{let a=JSON.parse($('terms-input').value);if(!Array.isArray(a)||a.length<1||a.length>32)throw Error('Enter an array containing 1 to 32 terms.');ts=a.map((q,i)=>{if(!q||Object.keys(q).sort().join(',')!=='coefficient,w,x,y,z')throw Error('Term '+(i+1)+' needs x, y, z, w, and coefficient.');if(!['x','y','z','w'].every(k=>Number.isSafeInteger(q[k])&&Math.abs(q[k])<=100))throw Error('Exponents must be integers from -100 to 100.');if(typeof q.coefficient!=='string'||! /^-?[0-9]{1,18}(?:\/[1-9][0-9]{0,17})?$/.test(q.coefficient))throw Error('Coefficients must be integer or fraction strings.');return[q.x,q.y,q.z,q.w,q.coefficient]});$('example').value='custom';$('formula').textContent='min of '+ts.length+' terms';showTerms();update($('exact').value)}catch(e){$('status').textContent=e.message}}
$('example').onchange=choose;$('height').oninput=e=>update(String(Math.round(+e.target.value*4)/4));$('exact').onchange=e=>update(e.target.value);$('reset').onclick=()=>{yaw=-.6;pitch=.5;draw()};$('plot').onpointerdown=e=>{last=[e.clientX,e.clientY];e.currentTarget.setPointerCapture(e.pointerId)};$('plot').onpointermove=e=>{if(last){yaw+=(e.clientX-last[0])*.008;pitch+=(e.clientY-last[1])*.008;last=[e.clientX,e.clientY];draw()}};$('plot').onpointerup=()=>last=null;window.onresize=draw;choose();