-- Generated by tropical-cyclic-oracle.py using exact integer determinants.
module TGeometry.TLRSCyclic (testsLRSCyclic) where

import Control.Monad (forM_)
import Data.List (sort)
import Data.Matrix (fromLists)
import Geometry.LRS (colFromList, lrs)
import Test.Tasty (TestTree, localOption, mkTimeout, testGroup)
import Test.Tasty.HUnit (assertEqual, testCase)

type Point = [Rational]
type Row = (Point, Rational)

checkFixture :: String -> [Row] -> [Point] -> TestTree
checkFixture name rows points = testGroup name
    [ testCase "all starting vertices" $ check rows points
    , testCase "reversed rows from first, middle and last vertices" $
        check (reverse rows) [head points, points !! (length points `div` 2), last points]
    ]
  where
    check constraints starts = forM_ starts $ \start ->
        assertEqual ("starting vertex " ++ show start) (sort points)
            (lrs (fromLists (map fst constraints))
                 (colFromList (map snd constraints)) start)

-- Every moment-curve input is an extreme point. Expected vertices are
-- constructed directly from t, independently of the supporting-plane oracle.

cyclic6D3 :: TestTree
cyclic6D3 = checkFixture "cyclic C(6,3)" rows points
  where
    points = [[t^k | k <- [1..3 :: Int]] | t <- [1..6]]
    rows =
        [([-41,12,-1],-30)
        ,([-29,10,-1],-20)
        ,([-19,8,-1],-12)
        ,([-11,6,-1],-6)
        ,([20,-9,1],12)
        ,([36,-11,1],36)
        ,([54,-13,1],72)
        ,([74,-15,1],120)
        ]

cyclic8D4 :: TestTree
cyclic8D4 = checkFixture "cyclic C(8,4)" rows points
  where
    points = [[t^k | k <- [1..4 :: Int]] | t <- [1..8]]
    rows =
        [([-482,167,-22,1],-336)
        ,([-358,137,-20,1],-240)
        ,([-252,109,-18,1],-160)
        ,([-164,83,-16,1],-96)
        ,([-94,59,-14,1],-48)
        ,([50,-35,10,-1],24)
        ,([78,-49,12,-1],40)
        ,([112,-65,14,-1],60)
        ,([152,-83,16,-1],84)
        ,([154,-71,14,-1],120)
        ,([198,-103,18,-1],112)
        ,([216,-91,16,-1],180)
        ,([288,-113,18,-1],252)
        ,([342,-119,18,-1],360)
        ,([370,-137,20,-1],336)
        ,([450,-145,20,-1],504)
        ,([572,-173,22,-1],672)
        ,([638,-179,22,-1],840)
        ,([804,-211,24,-1],1120)
        ,([1066,-251,26,-1],1680)
        ]

testsLRSCyclic :: TestTree
testsLRSCyclic = localOption (mkTimeout 30000000) $
    testGroup "LRS cyclic polytopes" [cyclic6D3, cyclic8D4]
